// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB50JGG-GzjhQwspGQhO6RUUermzrQWIac',
    appId: '1:478502450947:web:7cb039afe401e723815b36',
    messagingSenderId: '478502450947',
    projectId: 'talktify-fc293',
    authDomain: 'talktify-fc293.firebaseapp.com',
    storageBucket: 'talktify-fc293.appspot.com',
    measurementId: 'G-NZSDDZLC2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE0Iuc2ny7uAJDgcsVA82trICZ-E884WI',
    appId: '1:478502450947:android:981a488c863c04b1815b36',
    messagingSenderId: '478502450947',
    projectId: 'talktify-fc293',
    storageBucket: 'talktify-fc293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Y38r1Jx59xDrVMx8oY6vB_Nb_Qt4Ez0',
    appId: '1:478502450947:ios:2ea5a1642ddb9d3c815b36',
    messagingSenderId: '478502450947',
    projectId: 'talktify-fc293',
    storageBucket: 'talktify-fc293.appspot.com',
    iosBundleId: 'com.fawazalrasyid.talktify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Y38r1Jx59xDrVMx8oY6vB_Nb_Qt4Ez0',
    appId: '1:478502450947:ios:f7cb9ba446ffbd56815b36',
    messagingSenderId: '478502450947',
    projectId: 'talktify-fc293',
    storageBucket: 'talktify-fc293.appspot.com',
    iosBundleId: 'com.fawazalrasyid.talktify.RunnerTests',
  );
}
